"""empty message

Revision ID: 100f3802cc30
Revises: d6ff8ffd2e9c
Create Date: 2025-04-13 22:58:50.115598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '100f3802cc30'
down_revision: Union[str, None] = 'd6ff8ffd2e9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'moders', ['tg_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'moders', type_='unique')
    # ### end Alembic commands ###
