"""fixed fkey

Revision ID: 2cd4639f4a03
Revises: 6250c2838702
Create Date: 2025-08-22 20:43:26.388132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cd4639f4a03'
down_revision: Union[str, None] = '6250c2838702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('banlist_moder_id_fkey', 'banlist', type_='foreignkey')
    op.create_foreign_key(None, 'banlist', 'moders', ['moder_id'], ['tg_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'banlist', type_='foreignkey')
    op.create_foreign_key('banlist_moder_id_fkey', 'banlist', 'moders', ['moder_id'], ['id'])
    # ### end Alembic commands ###
