"""fixed id

Revision ID: 3072ace29767
Revises: 0daff8238715
Create Date: 2025-08-22 20:38:12.269423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3072ace29767'
down_revision: Union[str, None] = '0daff8238715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('banlist', 'moder_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('banlist', 'action',
               existing_type=postgresql.ENUM('ban', 'mute', 'tempban', name='banaction'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('banlist', 'action',
               existing_type=postgresql.ENUM('ban', 'mute', 'tempban', name='banaction'),
               nullable=True)
    op.alter_column('banlist', 'moder_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
