"""fixed fkey

Revision ID: 36e4dc0d3796
Revises: 7b463d4b946e
Create Date: 2025-08-22 20:45:03.673429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36e4dc0d3796'
down_revision: Union[str, None] = '7b463d4b946e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('log_moder_id_fkey', 'log', type_='foreignkey')
    op.create_foreign_key(None, 'log', 'moders', ['moder_id'], ['tg_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'log', type_='foreignkey')
    op.create_foreign_key('log_moder_id_fkey', 'log', 'moders', ['moder_id'], ['id'])
    # ### end Alembic commands ###
