"""added link to log_messages

Revision ID: 4a61d9e044ba
Revises: e9bbf60fad0a
Create Date: 2025-05-02 01:07:20.905403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a61d9e044ba'
down_revision: Union[str, None] = 'e9bbf60fad0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_messages', sa.Column('link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log_messages', 'link')
    # ### end Alembic commands ###
