"""added tempban action to logactions

Revision ID: fd774a227f80
Revises: 4a61d9e044ba
Create Date: 2025-08-22 17:56:44.776845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd774a227f80'
down_revision: Union[str, None] = '4a61d9e044ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banlist', sa.Column('action', sa.Enum('ban', 'mute', name='banaction'), nullable=False))
    op.alter_column('log', 'action',
               existing_type=postgresql.ENUM('kick', 'ban', 'post', 'mute', 'del_post', 'edit_post', 'add_admin', 'del_admin', 'call_cmd', name='action'),
               type_=sa.Enum('kick', 'ban', 'tmepban', 'post', 'mute', 'warn', 'del_post', 'edit_post', 'add_admin', 'del_admin', 'call_cmd', name='logaction'),
               existing_nullable=False)
    op.create_unique_constraint(None, 'tag_settings', ['tag'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag_settings', type_='unique')
    op.alter_column('log', 'action',
               existing_type=sa.Enum('kick', 'ban', 'tmepban', 'post', 'mute', 'warn', 'del_post', 'edit_post', 'add_admin', 'del_admin', 'call_cmd', name='logaction'),
               type_=postgresql.ENUM('kick', 'ban', 'post', 'mute', 'del_post', 'edit_post', 'add_admin', 'del_admin', 'call_cmd', name='action'),
               existing_nullable=False)
    op.drop_column('banlist', 'action')
    # ### end Alembic commands ###
